### ISSUE TITLE
78xx_Replacement_SD8942 pads not right?

### ISSUE THREAD

**Issue by jwvaughn** [wagiminator/Power-Boards#1]
Looking at the pictures, the inductor is nearly as wide as the circuit board which is about 10mm.  However the documentation for the PSPMAA0402-4R7M-ANP inductor indicates that it is only about 4.5mm wide which would be a problem with the pads I think.  Am I missing something here?

Jerry

**Comment by wagiminator** [comment]
Ups, it's a failure in the BOM. The correct inductor is the following:
PSPMAA0805-4R7M-ANP, LCSC# C2962882.
